# Dependencies
markdown:         redcarpet
highlighter:      pygments
excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ezra Zigmond
description:      'CS student and developer.'
url:              http://ezig.github.io/
baseurl:          /

author:
  name:           'Ezra Zigmond'
  url:            http://ezig.github.io/

paginate:         5

# Custom vars

github:			  
  repo:           https://github.com/ezig
